### ISSUE TITLE
no connection.

### ISSUE THREAD

**Issue by Gerard-Oedzes** [nikkow/node-red-contrib-tahoma#46]
Would love to use this!

Create an app: no problem. 
Enter the API key and secret: no problem. 
hit the button: link node-red to tahoma: 

An error has occurred
Please try again. If the problem persists, please contact our technical support team.

**Comment by n300home** [comment]
I've absolutely the same issue here. :(

**Comment by n300home** [comment]
I tested a little bit around and compared differences between this Node and other Web-Apps using somfy open API. The only obvious difference for me is, that the other App escapes special characters like / to HTML-kompatible string.

e.g.: This node-red Node generates the redirect_URL like this -> 

`redirect_uri=http://ccu3-webui/addons/red/somfy/callback`

whereas in the other App it looks like that -> 

`redirect_uri=https%3A%2F%2Fapi.enterprise.apigee.com%2Fv1%2Fo%2Fsomfy%2Fapimodels%2Fsomfy-open-api%2Ftemplateauths%2Foauth_scope_or_internal%2Fcallback
`

**Comment by panjazzon** [comment]
I have the same issue. Tahoma node linked to old somfy app shows "no devices". New  created app doesn't link and says: 

An error has occurred
Please try again. If the problem persists, please contact our technical support team.

Any solution? Is it  problem on somfy side or my config?

**Comment by pinkfloydFR** [comment]
I have the same issue here, like Gerard-Oedzes : 

Create an app: no problem.
Enter the API key and secret: no problem.
hit the button: link node-red to tahoma:

An error has occurred
Please try again. If the problem persists, please contact our technical support team.

Error code in node js : 

```
Cannot GET /somfy/callback&state=setup&grant_type=authorization_code

  
  TypeError: Cannot read property 'context' of null
    at /config/node-red/node_modules/node-red-contrib-tahoma/dist/nodes/tahoma-config.js:23:71
    at Layer.handle [as handle_request] (/opt/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/opt/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/node_modules/express/lib/router/layer.js:95:5)
    at /opt/node_modules/express/lib/router/index.js:281:22
    at param (/opt/node_modules/express/lib/router/index.js:354:14)
    at param (/opt/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/opt/node_modules/express/lib/router/index.js:410:3)
    at next (/opt/node_modules/express/lib/router/index.js:275:10)
```

**Comment by frankis78** [comment]
When i think about it, i Wonder if i had simular issue befor on older nodejs . What nodejs are you running?

**Comment by pinkfloydFR** [comment]
node --version
**v14.16.0**

I am running home assistant VM : 
  OS Version:               Home Assistant OS 5.12
  Home Assistant Core:      2021.3.4
  
Node red 1.2.9
 ghcr.io/hassio-addons/node-red/amd64:8.2.0

**Comment by frankis78** [comment]
Try to make a callback url by using webhook.site , and copy the url to your somfy app, to see if that works instead of your local. You still need to login to your somfy account in node red, when you authorize.

**Comment by pinkfloydFR** [comment]
Hummm..if my domain is "https://pinkfloyd.com", i enter "https://webhook.pinkfloyd.com" as callback url is this correct ?

**Comment by frankis78** [comment]
Hmm, as said im not an expert, but i have a server admin as a college that helped me at the point when i had similar issue. Then i used that a callback url i found in webhook.site, and after that i authorized. Maybe it authorized due to https? But after that , i changed it back to my local url, and it has worked ever since.

**Comment by pinkfloydFR** [comment]
oh ok i have misderstanding...

Testing with webhook.site, no answer at all !

**Comment by frankis78** [comment]
Did you use "your unique url"?
![image](https://user-images.githubusercontent.com/26933092/112734692-a5ad9a80-8f47-11eb-99ed-b1a229761ef9.png)

**Comment by pinkfloydFR** [comment]
yes exactly !

and now i am trying with info found here : https://developer.somfy.com/apis-docs

and for now, all my test failed with the same error as node red

ie, this NOT WORK : 

https://accounts.somfy.com/oauth/oauth/v2/auth?response_type=code&client_id=**YOUR_CONSUMER_KEY**&redirect_uri=**CALLBACKURL**&state=**YOUR_UNIQUE_VALUE**&grant_type=authorization_code

i begin to believe the problem is on somfy server



**EDIT : just find another people in the official somfy french support forum with exactly the same problem, post date 4 month ago, and no answer :(**

Subscribed and answered at the topic, wait & see...

**Comment by n300home** [comment]
Some weeks ago I contacted Somfy support regarding that issue. It seems they also have issues on their site. ->


--------------------------
Hello,
 
Thank you for contacting us. It looks like the App you created from our Developer Portal is not fully synchronized in the different elements of our SI. This is a bug that we randomly face and we cannot find any fix for now. The only remaining solutions would be to make other tries: either deleting the exiting apps of your account and creating a new one or creating a new one from a different account.
 
Best regards
--------------------------

I've created a new app on Somfy Dev-Portal. But received the same error. I haven't tried to create a new login (no I don't like to reconfiger my whole Somfy environment).

**Comment by kwithus** [comment]
Still same issue here, anyone has a solution on hand?

**Comment by pinkfloydFR** [comment]
Just received answer from developper today :

==============
Hello Denis,

Indeed, there is an issue with App creation on our side. Unfortunately, we cannot do much at this time and you have no other option but to wait for a fix to be released on this issue.

================

So nice from them to not apologize about a 5 month problem -_-

**Comment by kwithus** [comment]
Sounds like they don’t really want anyone to use this api, however thanks for your update.
I contacted them today as well, maybe they need more pressure

**Comment by krasnyt** [comment]
Also suffering from this...

**Comment by ozdeadmeat** [comment]
Has this been fixed yet? I am considering buying Somfy equipment but if their Developer Portal is always offline I will take a look at other options.

**Comment by pinkfloydFR** [comment]
No, you can without hesitate look for another option...

**Comment by kwithus** [comment]
I would recommend Homematic IP, with CCU3 it works totally offline and you also can set up/down-times directly in the device, which will operate even if HA or the CCU3 breaks down
