### ISSUE TITLE
Tahoma-Config-Node is not able to create local connection to Tahoma Box

### ISSUE THREAD

**Issue by Programmierfreund** [nikkow/node-red-contrib-tahoma#57]
**Describe the bug**
Today I have installed the new beta via npm i node-red-contrib-tahoma@beta on a clean docker container of node-red (https://hub.docker.com/r/nodered/node-red). I updated my tahoma box before and activated "Developer Mode" in my Somfy-Account.

**To Reproduce**
1. Go to 'tahoma-read note'
2. Click on 'add new account'
3. Fill in "Name", "Pin", "E-Mail', "Passwort"
4. See error on console

**Expected behavior**
Tahoma Box in same local network has to be found.

**Logs**
TypeError: Cannot read property 'url' of null
    at SomfyApi.getGatewayUrl (/usr/src/node-red/node_modules/node-red-contrib-tahoma/dist/core/somfy-api.js:146:41)
    at SomfyApi.getDevices (/usr/src/node-red/node_modules/node-red-contrib-tahoma/dist/core/somfy-api.js:157:33)
    at /usr/src/node-red/node_modules/node-red-contrib-tahoma/dist/nodes/tahoma-config.js:76:14
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/node-red/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/node-red/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/node-red/node_modules/express/lib/router/index.js:281:22
    at param (/usr/src/node-red/node_modules/express/lib/router/index.js:360:14)
    at param (/usr/src/node-red/node_modules/express/lib/router/index.js:371:14)
    at Function.process_params (/usr/src/node-red/node_modules/express/lib/router/index.js:416:3)
    at next (/usr/src/node-red/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/usr/src/node-red/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/node-red/node_modules/express/lib/router/index.js:323:13)
    at /usr/src/node-red/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/node-red/node_modules/express/lib/router/index.js:341:12)
    at next (/usr/src/node-red/node_modules/express/lib/router/index.js:275:10)
    at query (/usr/src/node-red/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/node-red/node_modules/express/lib/router/index.js:323:13)
    at /usr/src/node-red/node_modules/express/lib/router/index.js:284:7

**Setup:**
- Version of node-red: 2.2.2
- Version of node-red-contrib-tahoma: [v3.0.0-beta.4]
- Version of node (`node -v`): v14.18.2
- Version of npm (`npm -v`): .14.15
- Where is node-red installed: Docker Host, Linux Server
- How is node-red installed: https://hub.docker.com/r/nodered/node-red

**Comment by Programmierfreund** [comment]
I have found the error - because I have installed the beta on my development environment I have not opened enough ports for the docker container. I have changed to "bridge" instead of "NAT" mode and now the Tahoma-URL was set!
